"""empty message

Revision ID: de20f437c5f8
Revises: eca53ed660f3
Create Date: 2018-10-07 11:40:00.068654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de20f437c5f8'
down_revision = 'eca53ed660f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('common_post', sa.Column('readCount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('common_post', 'readCount')
    # ### end Alembic commands ###
