"""empty message

Revision ID: efb1b8ef4cdf
Revises: b31d692ccd73
Create Date: 2018-09-29 09:20:54.848482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb1b8ef4cdf'
down_revision = 'b31d692ccd73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boarder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('boardername', sa.String(length=99), nullable=False),
    sa.Column('postnum', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boarder')
    # ### end Alembic commands ###
