"""empty message

Revision ID: fac41427a30b
Revises: efb1b8ef4cdf
Create Date: 2018-09-29 16:44:27.000046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac41427a30b'
down_revision = 'efb1b8ef4cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boarder', sa.Column('jijji', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boarder', 'jijji')
    # ### end Alembic commands ###
